In [ ]:
# Dati forniti
data = """airline\tavail_seat_km_per_week\tincidents_85_99\tfatal_accidents_85_99\tfatalities_85_99\tincidents_00_14\tfatal_accidents_00_14\tfatalities_00_14
Aer Lingus\t320906734\t2\t0\t0\t0\t0\t0
Aeroflot*\t1197672318\t76\t14\t128\t6\t1\t88
Aerolineas Argentinas\t385803648\t6\t0\t0\t1\t0\t0
Aeromexico*\t596871813\t3\t1\t64\t5\t0\t0
Air Canada\t1865253802\t2\t0\t0\t2\t0\t0
Air France\t3004002661\t14\t4\t79\t6\t2\t337
Air India*\t869253552\t2\t1\t329\t4\t1\t158
Air New Zealand*\t710174817\t3\t0\t0\t5\t1\t7
Alaska Airlines*\t965346773\t5\t0\t0\t5\t1\t88
Alitalia\t698012498\t7\t2\t50\t4\t0\t0
All Nippon Airways\t1841234177\t3\t1\t1\t7\t0\t0
American*\t5228357340\t21\t5\t101\t17\t3\t416
Austrian Airlines\t358239823\t1\t0\t0\t1\t0\t0
Avianca\t396922563\t5\t3\t323\t0\t0\t0
British Airways*\t3179760952\t4\t0\t0\t6\t0\t0
Cathay Pacific*\t2582459303\t0\t0\t0\t2\t0\t0
China Airlines\t813216487\t12\t6\t535\t2\t1\t225
Condor\t417982610\t2\t1\t16\t0\t0\t0
COPA\t550491507\t3\t1\t47\t0\t0\t0
Delta / Northwest*\t6525658894\t24\t12\t407\t24\t2\t51
Egyptair\t557699891\t8\t3\t282\t4\t1\t14
El Al\t335448023\t1\t1\t4\t1\t0\t0
Ethiopian Airlines\t488560643\t25\t5\t167\t5\t2\t92
Finnair\t506464950\t1\t0\t0\t0\t0\t0
Garuda Indonesia\t613356665\t10\t3\t260\t4\t2\t22
Gulf Air\t301379762\t1\t0\t0\t3\t1\t143
Hawaiian Airlines\t493877795\t0\t0\t0\t1\t0\t0
Iberia\t1173203126\t4\t1\t148\t5\t0\t0
Japan Airlines\t1574217531\t3\t1\t520\t0\t0\t0
Kenya Airways\t277414794\t2\t0\t0\t2\t2\t283
KLM*\t1874561773\t7\t1\t3\t1\t0\t0
Korean Air\t1734522605\t12\t5\t425\t1\t0\t0
LAN Airlines\t1001965891\t3\t2\t21\t0\t0\t0
Lufthansa*\t3426529504\t6\t1\t2\t3\t0\t0
Malaysia Airlines\t1039171244\t3\t1\t34\t3\t2\t537
Pakistan International\t348563137\t8\t3\t234\t10\t2\t46
Philippine Airlines\t413007158\t7\t4\t74\t2\t1\t1
Qantas*\t1917428984\t1\t0\t0\t5\t0\t0
Royal Air Maroc\t295705339\t5\t3\t51\t3\t0\t0
SAS*\t682971852\t5\t0\t0\t6\t1\t110
Saudi Arabian\t859673901\t7\t2\t313\t11\t0\t0
Singapore Airlines\t2376857805\t2\t2\t6\t2\t1\t83
South African\t651502442\t2\t1\t159\t1\t0\t0
Southwest Airlines\t3276525770\t1\t0\t0\t8\t0\t0
Sri Lankan / AirLanka\t325582976\t2\t1\t14\t4\t0\t0
SWISS*\t792601299\t2\t1\t229\t3\t0\t0
TACA\t259373346\t3\t1\t3\t1\t1\t3
TAM\t1509195646\t8\t3\t98\t7\t2\t188
TAP - Air Portugal\t619130754\t0\t0\t0\t0\t0\t0
Thai Airways\t1702802250\t8\t4\t308\t2\t1\t1
Turkish Airlines\t1946098294\t8\t3\t64\t8\t2\t84
United / Continental*\t7139291291\t19\t8\t319\t14\t2\t109
US Airways / America West*\t2455687887\t16\t7\t224\t11\t2\t23
Vietnam Airlines\t625084918\t7\t3\t171\t1\t0\t0
Virgin Atlantic\t1005248585\t1\t0\t0\t0\t0\t0
Xiamen Airlines\t430462962\t9\t1\t82\t2\t0\t0"""

# Creazione DataFrame
df = pd.read_csv(StringIO(data), sep="\t")

# Stampare le prime 5 righe
print("Prime 5 righe del DataFrame:")
print(df.head())

# Stampare le ultime 5 righe
print("\nUltime 5 righe del DataFrame:")
print(df.tail())

# Mostrare la forma del DataFrame
print("\nForma del DataFrame:", df.shape)

# Mostrare statistiche descrittive
print("\nStatistiche descrittive:")
print(df.describe())

# Mostrare informazioni sulle colonne
print("\nInformazioni sulle colonne:")
print(df.info())

# Selezionare compagnie con incidenti_85_99 < 10
filtered_df = df[df["incidents_85_99"] < 10][["airline", "incidents_85_99"]]
print("\nCompagnie con meno di 10 incidenti (1985-1999):")
print(filtered_df)

# Raggruppare per la prima lettera in minuscolo e calcolare la media di incidents_85_99
df["first_letter"] = df["airline"].str[0].str.lower()  # Estrarre la prima lettera in minuscolo
grouped_df = df.groupby("first_letter")["incidents_85_99"].mean().reset_index()

# Rinominare le colonne per chiarezza
grouped_df.columns = ["first_letter", "mean_incidents_85_99"]
print("\nMedia degli incidenti 1985-1999 raggruppata per la prima lettera della compagnia:")
print(grouped_df)

In [ ]:
import pandas as pd

# Creazione del DataFrame con i dati forniti
data = {
    "Year": [1986, 1986, 1985, 1986, 1987, 1987, 1987, 1985, 1986, 1984, 1987, 1989, 1985, 1984, 1985, 1987, 1984, 1989, 1984, 1984, 1986, 1989, 1984, 1984, 1985, 1984, 1987, 1986, 1986, 1986, 1985, 1986, 1985, 1987, 1986, 1987, 1987, 1987, 1986, 1986, 1984, 1984, 1985, 1989, 1987, 1986, 1987, 1987, 1986, 1987, 1986, 1987, 1989, 1984, 1989, 1987, 1987, 1986, 1986, 1985, 1986, 1986, 1987, 1986, 1985, 1987, 1986, 1986, 1985, 1986, 1989, 1989, 1986, 1986, 1986, 1986, 1985, 1989, 1989, 1986, 1986, 1986, 1985, 1986, 1987, 1986, 1989, 1985, 1989, 1989, 1986, 1987, 1986, 1989, 1987, 1985, 1989, 1985, 1985, 1986, 1986, 1986, 1986, 1984, 1985],
    "WHO region": ["Western Pacific", "Americas", "Africa", "Americas", "Americas", "Americas", "Africa", "Africa", "Americas", "Africa", "Africa", "Americas", "Western Pacific", "Eastern Mediterranean", "Western Pacific", "Africa", "Americas", "Africa", "Europe", "Africa", "South-East Asia", "Americas", "Europe", "Europe", "Africa", "Eastern Mediterranean", "Western Pacific", "Europe", "Africa", "Western Pacific", "Africa", "Europe", "Americas", "Eastern Mediterranean", "Europe", "Eastern Mediterranean", "Africa", "Europe", "Europe", "Europe", "Western Pacific", "Europe", "Africa", "Americas", "Eastern Mediterranean", "Americas", "Europe", "Western Pacific", "Africa", "Americas", "Eastern Mediterranean", "Eastern Mediterranean", "Western Pacific", "Americas", "Eastern Mediterranean", "Africa", "Africa", "Africa", "Eastern Mediterranean", "Americas", "Eastern Mediterranean", "Eastern Mediterranean", "Africa", "Africa", "Eastern Mediterranean", "Americas", "Americas", "Europe", "Americas", "Eastern Mediterranean", "Europe", "Europe", "Eastern Mediterranean", "Africa", "Africa", "Europe", "Europe", "Africa", "Europe", "Africa", "Europe", "Europe", "Eastern Mediterranean", "Europe", "Western Pacific", "Africa", "Africa", "Europe", "Europe", "Western Pacific", "Africa", "Africa", "Europe", "South-East Asia", "South-East Asia", "Africa", "Europe", "Africa", "Europe", "Western Pacific", "Africa"]
}

# Creazione del DataFrame
df = pd.DataFrame(data)

# Filtrare i dati dove "WHO region" Ã¨ Africa, Eastern Mediterranean o Europe
filtered_df = df[df["WHO region"].isin(["Africa", "Eastern Mediterranean", "Europe"])]

# Stampare i primi 10 risultati
print(filtered_df.head(10))